site_name: Magicflow
site_url: https://cto2bpublic.github.io/magicflow/

nav:
  - Home: index.md
  - Integrations: 
    - integrations/architecture.md
  - Framework:
    - Components: framework/components.md
    - Jobs: framework/jobs.md
  - Examples:
    - Overview: examples/index.md
    - SSM: examples/ssm.md
    - Pipeline: examples/pipeline.md

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: light green
    accent: light green
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate

repo_url: https://github.com/CTO2BPublic/magicflow
repo_name: CTO2BPublic/magicflow

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
